// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	ReqSayWorld
	ReplySayWorld
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqSayWorld struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ReqSayWorld) Reset()                    { *m = ReqSayWorld{} }
func (m *ReqSayWorld) String() string            { return proto1.CompactTextString(m) }
func (*ReqSayWorld) ProtoMessage()               {}
func (*ReqSayWorld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqSayWorld) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ReplySayWorld struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ReplySayWorld) Reset()                    { *m = ReplySayWorld{} }
func (m *ReplySayWorld) String() string            { return proto1.CompactTextString(m) }
func (*ReplySayWorld) ProtoMessage()               {}
func (*ReplySayWorld) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReplySayWorld) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*ReqSayWorld)(nil), "proto.ReqSayWorld")
	proto1.RegisterType((*ReplySayWorld)(nil), "proto.ReplySayWorld")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	SayWorld(ctx context.Context, in *ReqSayWorld, opts ...grpc.CallOption) (*ReplySayWorld, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayWorld(ctx context.Context, in *ReqSayWorld, opts ...grpc.CallOption) (*ReplySayWorld, error) {
	out := new(ReplySayWorld)
	err := grpc.Invoke(ctx, "/proto.Hello/SayWorld", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	SayWorld(context.Context, *ReqSayWorld) (*ReplySayWorld, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSayWorld)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hello/SayWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayWorld(ctx, req.(*ReqSayWorld))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayWorld",
			Handler:    _Hello_SayWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto1.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8a, 0x5c, 0xdc, 0x41,
	0xa9, 0x85, 0xc1, 0x89, 0x95, 0xe1, 0xf9, 0x45, 0x39, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x26, 0x17, 0x6f, 0x50,
	0x6a, 0x41, 0x4e, 0x25, 0x5c, 0x91, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c,
	0x1d, 0x8c, 0x6b, 0x64, 0xcf, 0xc5, 0xea, 0x01, 0xb2, 0x43, 0xc8, 0x8c, 0x8b, 0x03, 0x61, 0x26,
	0xc4, 0x46, 0x3d, 0x24, 0x7b, 0xa4, 0x44, 0xe0, 0x62, 0x48, 0x06, 0x2b, 0x31, 0x24, 0xb1, 0x81,
	0x85, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x7c, 0xe7, 0x6b, 0xab, 0x00, 0x00, 0x00,
}
